dateModified: 1791196099
meta:
  __names__:
    01a10b9a-a7d1-7260-b4ec-4a68b5ec2730: Image # Image
    01a10b99-261f-7271-885a-75961ae2892c: Body # Body
    507190df-3802-44b1-a9df-c56a042d3c6d: Home # Home
    d0261b43-45c5-4ee4-96dd-b74042705196: Default # Default
    d1b40666-8b39-4ce4-b084-1b6f782aea9e: Home # Home
    dd84d747-4f3d-4c6c-bb91-014e050ed11e: Default # Default
    fa25ff96-88dd-4065-a4c8-c2f710b17247: Images # Images
    fad52ce1-f8eb-4e3c-877c-ff2e7885a850: 'Project Transformer' # Project Transformer
system:
  edition: solo
  name: Default
  schemaVersion: 6.0.0.21
  timeZone: $TZ
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
