dateModified: 1791559608
elementSources:
  CraftCms\Cms\Entry\Elements\Entry:
    - defaultSort:
        - postDate
        - desc
      defaultViewMode: table
      disabled: false
      key: '*'
      page: Entries
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    - defaultSort:
        - title
        - asc
      defaultViewMode: table
      disabled: false
      key: singles
      page: Entries
      tableAttributes:
        - status
        - section
        - link
      type: native
    - heading: Channels
      key: 'heading:c80c9ee7-862c-41ab-9612-ee033975ae88'
      page: Entries
      type: heading
    - defaultSort:
        - postDate
        - desc
      defaultViewMode: table
      disabled: false
      key: 'section:90a86bc2-6e67-4370-889e-314a3736fc2d' # Article
      page: Entries
      tableAttributes:
        - status
        - 'fieldInstance:822a7287-3023-4a8a-8731-3ca6867d2f49'
        - postDate
        - link
      type: native
mcp:
  publicAllowDrafts: false
  publicAllowInactive: false
  publicAllowRevisions: false
  publicEnabled: true
  publicNestedEntryFieldHandles:
    - contentBuilder
  publicRoute: /mcp
  publicSectionHandles:
    - article
  publicSiteHandles:
    - default
  publicTools:
    - craft-context-get
    - craft-query
  publicVolumeHandles:
    - images
meta:
  __names__:
    01a10b9a-a7d1-7260-b4ec-4a68b5ec2730: Image # Image
    01a10b99-261f-7271-885a-75961ae2892c: Body # Body
    4f754d1d-89a4-49e1-8199-8a3b18ca1678: Heading # Heading
    8c75a619-1b13-4e21-a89b-788916565405: Article # Article
    11d54dce-ad29-43fc-8a7e-8e802d3eb983: Text # Text
    019e02e9-af69-702d-8c7b-319a5387ae69: 'Multi Line Text' # Multi Line Text
    019e02ea-0f08-7368-a6c7-fc2aeca299df: 'Content Builder' # Content Builder
    019e1627-dbcc-70f4-9cca-4316474768e3: 'Single Line Text' # Single Line Text
    019e1628-65ec-7330-83c6-a72d7d1e9965: 'Heading Level' # Heading Level
    87a488b7-81cd-4edf-abb6-22c1e7f2b36c: Contact # Contact
    90a86bc2-6e67-4370-889e-314a3736fc2d: Article # Article
    7576fa7c-acd7-47b1-a9d1-88f0a92821b2: Image # Image
    18007da3-6f17-4249-b66c-a3d092378d4b: Search # Search
    507190df-3802-44b1-a9df-c56a042d3c6d: 'Simple Page' # Simple Page
    cd0de69b-34b4-4a90-8c48-6a3daa624aa0: 'Article Index' # Article Index
    d0261b43-45c5-4ee4-96dd-b74042705196: Default # Default
    d1b40666-8b39-4ce4-b084-1b6f782aea9e: Home # Home
    dd84d747-4f3d-4c6c-bb91-014e050ed11e: Default # Default
    fa25ff96-88dd-4065-a4c8-c2f710b17247: Images # Images
    fad52ce1-f8eb-4e3c-877c-ff2e7885a850: 'Images Transformer' # Images Transformer
system:
  edition: solo
  name: $APP_NAME
  retryDuration: null
  schemaVersion: 6.0.0.23
  timeZone: $TZ
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
