handle: headingLevel
instructions: null
name: 'Heading Level'
searchable: false
settings:
  customOptions: false
  options:
    - __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - '1'
    - __assoc__:
        -
          - label
          - h3
        -
          - value
          - h3
translationKeyFormat: null
translationMethod: none
type: CraftCms\Cms\Field\Dropdown
