handle: singleLineText
instructions: null
name: 'Single Line Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: CraftCms\Cms\Field\PlainText
