defaultPlacement: end
enableVersioning: true
entryTypes:
  - uid: 8c75a619-1b13-4e21-a89b-788916565405 # Article
handle: article
maxAuthors: 1
minAuthors: 1
name: Article
previewTargets:
  - label: 'Primary entry page'
    refresh: true
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d0261b43-45c5-4ee4-96dd-b74042705196: # Default
    enabledByDefault: true
    hasUrls: true
    route: null
    template: entries/article/show
    uriFormat: 'articles/{slug}'
type: channel
workflow: null
