defaultPlacement: end
enableVersioning: true
entryTypes:
  - uid: 507190df-3802-44b1-a9df-c56a042d3c6d # Simple Page
handle: search
maxAuthors: null
minAuthors: 0
name: Search
previewTargets:
  - label: 'Primary entry page'
    refresh: true
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d0261b43-45c5-4ee4-96dd-b74042705196: # Default
    enabledByDefault: true
    hasUrls: true
    route: search
    template: null
    uriFormat: search
type: single
workflow: null
