#!/bin/bash

if [ -z $3 ]
then
    echo Usage: install project-name username password
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1
ddev composer install &&
ddev artisan key:generate --ansi &&
ddev artisan craft:install  --username=$2 --password=$3 --email=admin@example.com --siteName=Default --siteUrl='$APP_URL' --language=en-US --timezone='$TZ' &&
ddev artisan storage:link &&
ddev npm install &&
ddev npm run build &&
ddev describe &&
ddev launch

